services:
  # frontend:
  #   container_name: frontend-container
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4200:80"
  #   restart: unless-stopped

  auth-api:
    container_name: auth-api
    build:
      context: .
      dockerfile: ./AuthAPI/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - authdb
    env_file:
      - ./.env
    environment:
      MYSQL_HOST: authdb
      MYSQL_DATABASE: auth

  client-api:
    container_name: client-api
    build:
      context: .
      dockerfile: ./ClientAPI/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
      - event-api
    environment:
      MONGO_DETAILS: "mongodb://mongo:27017"
      EVENT_API_BASE_URL: "http://event-api:8080"
      AUTH_API_ADDRESS: "auth-api:50051"

  event-api:
    container_name: event-api
    build:
      context: .
      dockerfile: ./EventAPI/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - auth-api
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/pos_project"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      AUTH_API_ADDRESS: "auth-api:50051"

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: pos_project
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  authdb:
    container_name: authdb
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: auth
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - authdb-data:/var/lib/mysql

volumes:
  mongo-data:
  mariadb-data:
  authdb-data: