syntax = "proto3";

package com.example.auth;

option java_package = "com.example.auth.grpc";
option java_multiple_files = true;

service AuthService {
  // returns a JWT
  rpc Login(LoginRequest) returns (LoginResponse);

  // admin-only
  rpc CreateUser(CreateUserRequest) returns (UserResponse);

  // returns the user's claims
  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
}

// User data for responses
message User {
  int32 id = 1;
  string email = 2;
  string role = 3;
}

// Messages for Login
message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string token = 1;
}

// Messages for User Creation
message CreateUserRequest {
  string email = 1;
  string password = 2;
  string role = 3; // OWNER_EVENT or CLIENTs
  // Admin token for authorization
  string admin_token = 4;
}

message UserResponse {
  User user = 1;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  bool is_valid = 1;
  int32 user_id = 2;
  string email = 3;
  string role = 4;
}
